<?php
/** @var Subscribe $block */
/** @var Escaper $escaper */
/** @var CategoryList $CategoryList */

use Magento\Framework\Escaper;
use Magento\Newsletter\Block\Subscribe;
use RltSquare\NewsletterPopup\Block\CategoryList;

try {
    $CategoryList = $block->getLayout()->createBlock(CategoryList::class);
} catch (\Magento\Framework\Exception\LocalizedException $e) {
}

?>
<style>
    .dropdown-check-list {
        display: inline-block;
    }

    .dropdown-check-list .anchor {
        position: relative;
        cursor: pointer;
        display: inline-block;
        padding: 5px 300px 5px 10px;
        border: 1px solid #ccc;
    }

    .dropdown-check-list .anchor:after {
        position: absolute;
        content: "";
        border-left: 2px solid black;
        border-top: 2px solid black;
        padding: 5px;
        right: 10px;
        top: 20%;
        -moz-transform: rotate(-135deg);
        -ms-transform: rotate(-135deg);
        -o-transform: rotate(-135deg);
        -webkit-transform: rotate(-135deg);
        transform: rotate(-135deg);
    }

    .dropdown-check-list .anchor:active:after {
        right: 8px;
        top: 21%;
    }

    .dropdown-check-list ul.items {
        padding: 2px;
        display: none;
        margin: 0;
        border: 1px solid #ccc;
        border-top: none;
    }

    .dropdown-check-list ul.items li {
        list-style: none;
    }

    .dropdown-check-list.visible .anchor {
        color: #0094ff;
    }

    .dropdown-check-list.visible .items {
        display: block;
    }
</style>
<div class="block newsletter">
    <div class="title"><strong><?= $escaper->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <form class="form subscribe"
              novalidate
              action="<?= $escaper->escapeUrl($block->getFormActionUrl()) ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                        <span class="label">
                            <?= $escaper->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?= $escaper->escapeHtml(__('Enter your email address')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />
                    </label>
                </div>
            </div>
            <div class="field newsletter">
                <div class="control">
                    <label for="subscriber_name">
                        <span class="label">
                            <?= $escaper->escapeHtml(__('Gender:')) ?>
                        </span>
                        <label for="gender_male">Male</label>
                        <input type="radio" id="gender_male" name="gender" value="male"
                               placeholder="<?= $escaper->escapeHtml(__('Male')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true}"
                        />
                        <label for="gender_female">Female</label>
                        <input type="radio" id="gender_female" name="gender" value="female"
                               placeholder="<?= $escaper->escapeHtml(__('Female')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true}"
                        />
                    </label>
                </div>
            </div>
            <div style="margin-top: 10px" id="list1" class="dropdown-check-list" tabindex="100">
                <span class="anchor">Select Categories</span>
                <ul class="items">
                    <?php try {
                        $levelTwoCategories = $CategoryList->getLevelTwoCategories();
                        foreach ($levelTwoCategories as $category) : ?>
                            <li>
                                <label>
                                    <input type="checkbox" name="selected_categories[]"
                                           value="<?php echo $category->getName(); ?>"/>
                                </label>
                                <?php echo $escaper->escapeHtml($category->getName()); ?>
                            </li>
                        <?php endforeach;
                    } catch (\Magento\Framework\Exception\LocalizedException $e) {
                    } ?>
                </ul>
            </div>

            <div class="actions">
                <button class="action subscribe primary" style="margin-top: 10px"
                        title="<?= $escaper->escapeHtmlAttr(__('Subscribe')) ?>"
                        type="submit"
                        aria-label="Subscribe">
                    <span><?= $escaper->escapeHtml(__('Subscribe')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
<script>
    var checkList = document.getElementById('list1');
    checkList.getElementsByClassName('anchor')[0].onclick = function(evt) {
        if (checkList.classList.contains('visible'))
            checkList.classList.remove('visible');
        else
            checkList.classList.add('visible');
    }
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }
</script>
