<?php
/** @var Subscribe $block */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use RltSquare\NewsletterPopup\Model\Config\Backend\Image\Newsletterbg;
use RltSquare\NewsletterPopup\Model\Config\Backend\Image\Newsletterlogo;

$_helper = $this->helper('RltSquare\NewsletterPopup\Helper\Data');

$popup = $_helper->getConfig('newsletter_popup/newsletter');
if (isset($popup['enable']) && $popup['enable'] != 0) {
    $delay = $popup["delay"];
    ?>
    <script type="text/javascript">
        require([
            'jquery',
            'RltSquare_NewsletterPopup/fancybox/js/jquery.cookie',
            'RltSquare_NewsletterPopup/fancybox/js/jquery.fancybox'
        ], function ($) {
            $(document).ready(function () {
                // submit button

                $('#newsletter-validate-popup-detail').submit(function (e) {
                    if ($('#newsletter-validate-popup-detail').valid()) {
                        let html = '<div class="messages"><div class="message message-success success"><div data-ui-id="checkout-cart-validationmessages-message-success">"Thank you for your subscription."</div></div>';
                        $("#show_message").html(html);
                        $.cookie('newsletter_popup', 'dontshowitagain');
                    }else{
                        $("#show_message").html('');
                        $.cookie('newsletter_popup', 'shown');
                    }
                });
                // close button
                $(document).on('click', '#nl_close_btn', function () {
                    $.cookie('newsletter_popup', 'dontshowitagain');
                });

                <?php if($popup['enable'] == 1): ?>
                if ($("body").hasClass("cms-index-index")) {
                    <?php endif; ?>
                    let check_cookie = $.cookie('newsletter_popup');
                    if (window.location !== window.parent.location) {
                        $('#newsletter_popup').remove();
                    } else {
                        if (check_cookie == null || check_cookie === 'shown') {
                            setTimeout(function () {
                                beginNewsletterForm();
                            }, <?php echo $delay; ?>);
                        }
                        $('#newsletter_popup_dont_show_again').on('change', function () {
                            if ($(this).length) {
                                let check_cookie = $.cookie('newsletter_popup');
                                if (check_cookie == null || check_cookie === 'shown') {
                                    $.cookie('newsletter_popup', 'dontshowitagain');
                                } else {
                                    $.cookie('newsletter_popup', 'shown');
                                    beginNewsletterForm();
                                }
                            } else {
                                $.cookie('newsletter_popup', 'shown');
                            }
                        });
                    }
                    <?php if($popup['enable'] == 1): ?>
                }
                <?php endif; ?>
            });

            function beginNewsletterForm() {
                $.fancybox({
                    'padding': '0px',
                    'autoScale': true,
                    'transitionIn': 'fade',
                    'transitionOut': 'fade',
                    'type': 'inline',
                    'href': '#newsletter_popup',
                    'onComplete': function () {
                        $.cookie('newsletter_popup', 'shown');
                    },
                    'tpl': {
                        closeBtn: '<a title="Close" id="nl_close_btn" class="fancybox-item fancybox-close fancybox-newsletter-close" href="javascript:;"></a>'
                    },
                    'helpers': {
                        overlay: {
                            locked: false
                        }
                    }
                });
                $('#newsletter_popup').trigger('click');
            }
        });
    </script>
    <style type="text/css">
        <?php
            if(isset($popup["custom_style"])){
                echo $popup["custom_style"];
            }
        ?>
        #newsletter_popup {
        <?php
            if(isset($popup["width"])){
                echo "width:".$popup["width"].";";
            }
            if(isset($popup["height"])){
                echo "min-height:".$popup["height"].";";
            }
            if(isset($popup["bg_color"])){
                echo "background-color:".$popup["bg_color"].";";
            }
            if(isset($popup["bg_image"]) && $popup["bg_image"]){
                $folderName = Newsletterbg::UPLOAD_DIR;
                $path = $folderName . '/' . $popup["bg_image"];
                $imageUrl = $_helper->getBaseUrl() . $path;
        ?> background-image: url(<?php echo $imageUrl;?>);
        <?php
            }
        ?>
        }
    </style>
    <div class="newsletter row no-padding" id="newsletter_popup" style="display: none;">
        <div class="col-sm-8 pr-lg-4 vc_column_container col-md-7 col-10">
            <?php
            if (isset($popup["logo_src"]) && $popup["logo_src"]) {
                $folderName = Newsletterlogo::UPLOAD_DIR;
                $path = $folderName . '/' . $popup["logo_src"];
                $logoUrl = $_helper->getBaseUrl() . $path;
                ?>
                <div class="text_left mb-4 pb-1">
                    <img src="<?php echo $logoUrl; ?>" alt=""/>
                </div>
                <?php
            }
            ?>
            <?php echo $popup["content"]; ?>
            <form class="form subscribe mb-1"
                  novalidate
                  action="<?php echo $block->getFormActionUrl() ?>"
                  method="post"
                  data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                  id="newsletter-validate-popup-detail">
                <div class="field newsletter">
                    <div class="control">
                        <input name="email" type="email" id="footer_newsletter"
                               placeholder="<?php echo __("Your email address"); ?>"
                               data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="field newsletter">
                    <div class="control">
                        <label for="gender">
                        <span class="label">
                            <?= $escaper->escapeHtml(__('Gender:')) ?>
                        </span>
                            <label for="gender_male">Male</label>
                            <input type="radio" id="gender_male" name="gender" value="male"
                                   placeholder="<?= $escaper->escapeHtml(__('Male')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'
                                   data-validate="{required:true}"
                            />
                            <label for="gender_female">Female</label>
                            <input type="radio" id="gender_female" name="gender" value="female"
                                   placeholder="<?= $escaper->escapeHtml(__('Female')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'
                                   data-validate="{required:true}"
                            />
                        </label>
                    </div>
                </div>
                <div class="actions">
                    <button class="action subscribe primary" id="btn_submit" title="<?php echo __('Submit') ?>" type="submit">
                        <span><?php echo __('Submit') ?></span>
                    </button>
                </div>
                <div id="show_message"></div>
            </form>
            <p class="mb-0">
                <label class="checkbox checkbox-inline">
                    <input type="checkbox"
                           id="newsletter_popup_dont_show_again"/><?php echo __("Don't show this popup again"); ?>
                </label
        </div>
    </div>
    </div>
    <?php
}
?>
